server:
  http:
    addr: 0.0.0.0:8000
    timeout: 30s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 30s
    # unit is seconds: 30 seconds
    max_idle_connection: 30
    # unit is seconds: 120 seconds
    max_connection_age: 120
    shared_write_buffer: true
data:
  mongo:
    connection: mongodb+srv://allen-staging-staging-cluster-pl-0.xklzc.mongodb.net
    db_name: collectionview_db
    max_pool_size: 20
    min_pool_size: 5
    max_conn_idle_time: 30
    timeout: 6000
    is_connection_pool_enabled: true
    cred_file_location: /mnt/secrets-store/mongo_db_credentials
    cred_file_type: json



