server:
  http:
    addr: 0.0.0.0:8001
    timeout: 10000s
  grpc:
    addr: 0.0.0.0:9001
    timeout: 100000s
data:
  mongo:
    cred_file_location: /Users/shivanshmani/Desktop/allen/collectionview-service/configs/mongo_db_credentials.log
    connection: mongodb://root:N%3AakESjF%2Fm%2C3@10.1.54.42:27017/?authMechanism=SCRAM-SHA-1&directConnection=true
    timeout: 6000

